serviceTree:
  landscape: pichu
  platform: systems
  service: policy-engine
  module: policies
  layer: "1"

kyverno-policies:
  podSecurityStandard: baseline
  #  includeRestrictedPolicies:
  #    - disallow-privilege-escalation
  #    - require-run-as-non-root-user
  #    - require-run-as-nonroot
  #    - restrict-volume-types
  podSecuritySeverity: medium
  validationFailureAction: Audit
  policyExclude:
    disallow-capabilities:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-host-namespaces:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-host-path:
      any:
        - resources:
            namespaces:
              - kube-system
        - resources:
            namespaces:
              - otel
            names:
              - otel-container-logs-collector*
    disallow-host-ports:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-host-process:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-privileged-containers:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-proc-mount:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-selinux:
      any:
        - resources:
            namespaces:
              - kube-system
    restrict-apparmor-profiles:
      any:
        - resources:
            namespaces:
              - kube-system
    restrict-sysctls:
      any:
        - resources:
            namespaces:
              - kube-system
    restrict-seccomp:
      any:
        - resources:
            namespaces:
              - kube-system
    disallow-privilege-escalation:
      any:
        - resources:
            namespaces:
              - kube-system
    require-run-as-non-root-user:
      any:
        - resources:
            namespaces:
              - kube-system
    require-run-as-nonroot:
      any:
        - resources:
            namespaces:
              - kube-system
    restrict-seccomp-strict:
      any:
        - resources:
            namespaces:
              - kube-system
    restrict-volume-types:
      any:
        - resources:
            namespaces:
              - kube-system
globalExcludedNamespace:
  - kube-system

policies:
  requireAtomiCloudAnnotations:
    enable: true
    exclude:
      names:
        - kyverno-cleanup-controller-*
  requireAtomiCloudLabels:
    enable: true
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkLandscapeLabel:
    enable: true
    value: pichu
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkLandscapeAnnotation:
    enable: true
    value: pichu
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkLayerLabel:
    enable: true
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkLayerAnnotation:
    enable: true
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkPlatformLabel:
    enable: true
    acceptedValues:
      - systems
      - amide
      - alkene
    exclude:
      names:
        - kyverno-cleanup-controller-*
  checkPlatformAnnotation:
    enable: true
    acceptedValues:
      - systems
      - amide
      - alkene
    exclude:
      names:
        - kyverno-cleanup-controller-*
  disableCriSockMount:
    enable: true
    exclude: { }
  disallowEmptyIngress:
    enable: true
    exclude: { }
  disallowLatestTag:
    enable: true
    exclude: {}
  disallowNodePorts:
    enable: true
    exclude: { }
  requireRequestLimits:
    enable: true
    exclude:
      names:
        - otel-target-allocator-targetallocator-*
