serviceTree:
  landscape: &landscape entei
  cluster: opal


commonExclude:
  annotaions: &annotationExclude
    - "*-cleanup-controller-*"
  labels: &labelExclude
    - "*-cleanup-controller-*"

globalExcludedNamespace:
  - kube-system
  - pichu
  - pikachu
  - raichu

kyverno-policies:
  podSecurityStandard: baseline
  podSecuritySeverity: medium
  validationFailureAction: Audit

policies:
  requireAtomiCloudAnnotations:
    exclude:
      names: *annotationExclude

  requireAtomiCloudLabels:
    exclude:
      names: *labelExclude

  checkLandscapeLabel:
    value: *landscape
    exclude:
      names: *labelExclude

  checkLandscapeAnnotation:
    value: *landscape
    exclude:
      names: *annotationExclude

  checkLayerLabel:
    exclude:
      names: *labelExclude

  checkLayerAnnotation:
    exclude:
      names: *annotationExclude

  checkPlatformLabel:
    exclude:
      names: *labelExclude

  checkPlatformAnnotation:
    exclude:
      names: *annotationExclude

  requireRequestLimits:
    exclude:
      names:
        - "*-target-allocator-targetallocator-*"
