{{- if .Values.policies.checkLandscapeLabel.enable }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: correct-landscape-label
  annotations:
    policies.kyverno.io/title: Correct Landscape Label
    policies.kyverno.io/category: AtomiCloud Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Label
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Landscape Label needs to be set to the correct value.
spec:
  validationFailureAction: {{ index .Values "kyverno-policies" "validationFailureAction" }}
  background: true
  rules:
    - name: check-for-landscape-label
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{ .Values.globalExcludedNamespace | toYaml | nindent 16 }}
              {{- if.Values.policies.checkLandscapeLabel.exclude.namespaces }}
              {{ .Values.policies.checkLandscapeLabel.exclude.namespaces | toYaml | nindent 16 }}
              {{- end }}
          {{- if.Values.policies.checkLandscapeLabel.exclude.names }}
          - resources:
              names:
              {{ .Values.policies.checkLandscapeLabel.exclude.names | toYaml | nindent 16 }}
          {{- end }}
      validate:
        message: "The label `atomi.cloud/landscape` is incorrect. Expected '{{.Values.policies.checkLandscapeLabel.value}}' but got '{{ `{{request.object.metadata.labels.\"atomi.cloud/landscape\"}}` }}'"
        deny:
          conditions:
            all:
              - key: "{{ `{{ regex_match('^` }}{{.Values.policies.checkLandscapeLabel.value}}{{- `$','{{request.object.metadata.labels.\"atomi.cloud/landscape\" || 'empty'}}') }}`}}"
                operator: Equals
                value: false
{{- end }}
