{{- if .Values.policies.checkLayerLabel.enable }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: valid-layer-label
  annotations:
    policies.kyverno.io/title: Valid Layer Label
    policies.kyverno.io/category: AtomiCloud Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Label
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Layer Label needs to be between 1 and 4
spec:
  validationFailureAction: {{ index .Values "kyverno-policies" "validationFailureAction" }}
  background: true
  rules:
    - name: check-for-landscape-label
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{ .Values.globalExcludedNamespace | toYaml | nindent 16 }}
              {{- if.Values.policies.checkLayerLabel.exclude.namespaces }}
              {{ .Values.policies.checkLayerLabel.exclude.namespaces | toYaml | nindent 16 }}
              {{- end }}
          {{- if.Values.policies.checkLayerLabel.exclude.names }}
          - resources:
              names:
              {{ .Values.policies.checkLayerLabel.exclude.names | toYaml | nindent 16 }}
          {{- end }}
      validate:
        message: "The label `atomi.cloud/layer` needs to be between 1 and 4, but got '{{ `{{request.object.metadata.labels.\"atomi.cloud/layer\"}}` }}'"
        deny:
          conditions:
            all:
              - key: "{{ `{{ regex_match('^[1-4]$','{{request.object.metadata.labels.\"atomi.cloud/layer\" || 'empty'}}') }}`}}"
                operator: Equals
                value: false
{{- end }}
