{{- if .Values.policies.checkLayerAnnotation.enable }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: valid-layer-annotation
  annotations:
    policies.kyverno.io/title: Valid Layer Annotation
    policies.kyverno.io/category: AtomiCloud Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Annotation
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Layer Annotation needs to be between 1 and 4
spec:
  validationFailureAction: {{ index .Values "kyverno-policies" "validationFailureAction" }}
  background: true
  rules:
    - name: check-for-landscape-annotation
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{ .Values.globalExcludedNamespace | toYaml | nindent 16 }}
              {{- if.Values.policies.checkLayerAnnotation.exclude.namespaces }}
              {{ .Values.policies.checkLayerAnnotation.exclude.namespaces | toYaml | nindent 16 }}
              {{- end }}
          {{- if.Values.policies.checkLayerAnnotation.exclude.names }}
          - resources:
              names:
              {{ .Values.policies.checkLayerAnnotation.exclude.names | toYaml | nindent 16 }}
          {{- end }}
      validate:
        message: "The annotation `atomi.cloud/layer` needs to be between 1 and 4, but got '{{ `{{request.object.metadata.annotations.\"atomi.cloud/layer\"}}` }}'"
        deny:
          conditions:
            all:
              - key: "{{ `{{ regex_match('^[1-4]$','{{request.object.metadata.annotations.\"atomi.cloud/layer\" || 'empty'}}') }}`}}"
                operator: Equals
                value: false
{{- end }}
