{{- if .Values.policies.disallowNodePorts.enable }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-nodeport
  labels: {{- include "sulfoxide-sodium.labels" . | nindent 4 }}
  annotations: {{- include "sulfoxide-sodium.annotations" . | nindent 4 }}
    policies.kyverno.io/title: Disallow NodePort
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      A Kubernetes Service of type NodePort uses a host port to receive traffic from
      any source. A NetworkPolicy cannot be used to control traffic to host ports.
      Although NodePort Services can be useful, their use must be limited to Services
      with additional upstream security checks. This policy validates that any new Services
      do not use the `NodePort` type.
spec:
  validationFailureAction: {{ index .Values "kyverno-policies" "validationFailureAction" }}
  background: true
  rules:
    - name: validate-nodeport
      match:
        any:
          - resources:
              kinds:
                - Service
      exclude:
        any:
          - resources:
              namespaces:
              {{ .Values.globalExcludedNamespace | toYaml | nindent 16 }}
              {{- if.Values.policies.disallowNodePorts.exclude.namespaces }}
              {{ .Values.policies.disallowNodePorts.exclude.namespaces | toYaml | nindent 16 }}
              {{- end }}
          {{- if.Values.policies.disallowNodePorts.exclude.names }}
          - resources:
              names:
              {{ .Values.policies.disallowNodePorts.exclude.names | toYaml | nindent 16 }}
          {{- end }}
      validate:
        message: "Services of type NodePort are not allowed."
        pattern:
          spec:
            =(type): "!NodePort"
{{- end }}
