{{- if .Values.policies.checkPlatformLabel.enable }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: valid-platform-label
  annotations:
    policies.kyverno.io/title: Correct Platform Label
    policies.kyverno.io/category: AtomiCloud Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Label
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Platform Label needs to be one of {{ join ", " .Values.policies.checkPlatformLabel.acceptedValues }}.
spec:
  validationFailureAction: {{ index .Values "kyverno-policies" "validationFailureAction" }}
  background: true
  rules:
    - name: valid-platform-label
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{ .Values.globalExcludedNamespace | toYaml | nindent 16 }}
              {{- if.Values.policies.checkPlatformLabel.exclude.namespaces }}
              {{ .Values.policies.checkPlatformLabel.exclude.namespaces | toYaml | nindent 16 }}
              {{- end }}
          {{- if.Values.policies.checkPlatformLabel.exclude.names }}
          - resources:
              names:
              {{ .Values.policies.checkPlatformLabel.exclude.names | toYaml | nindent 16 }}
          {{- end }}
      validate:
        message: "The label `atomi.cloud/platform` is incorrect. Expected of one '{{ join ", " .Values.policies.checkPlatformLabel.acceptedValues }}' but got '{{ `{{request.object.metadata.labels.\"atomi.cloud/platform\"}}` }}'"
        deny:
          conditions:
            all:
              - key: "{{ `{{ regex_match('^(` }}{{ join "|" .Values.policies.checkPlatformLabel.acceptedValues }}{{- `)$','{{request.object.metadata.labels.\"atomi.cloud/platform\" || 'empty'}}') }}`}}"
                operator: Equals
                value: false
{{- end }}
